### ISSUE TITLE
Improve searching for titles with space dash space in title

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/searchworks_traject_indexer#1309] opened 2024-01-23 07:04 UTC
@jlkalchik reports that searching for titles with spaces around a dash do not work unless the search phrase is in quotation marks. 

See this query without quotation marks:https://searchworks.stanford.edu/?search_field=search&q=Sprache+-+text+-+system
Here is the query with quotation marks: https://searchworks.stanford.edu/?search_field=search&q=%22Sprache+-+text+-+system%22)
Record she was trying to retrieve is: https://searchworks.stanford.edu/view/14723886

In a SearchWorks triage meeting, Cory/Chris indicated that we'd need to see what solr is doing with the query, and hopefully that would give us some clues about how to handle this record via title search.

JIRA issue with original feedback: https://jirasul.stanford.edu/jira/browse/SW-4164

**Comment by hudajkhan** [comment] 2024-01-25 17:29
Note: Solr admin tools would be good as a starting point to see how queries are being handled.  This issue should require some investigation.

**Comment by hudajkhan** [comment] 2024-01-25 17:31
Also: We want to make sure we don't strip out support for the "minus" operator which allows queries to specify that they don't want a particular value/range.

**Comment by dnoneill** [comment] 2024-01-25 18:45
Some quick results from solr admin

Search query | returns result
Sprache- text | TRUE
Sprache - text | FALSE
Sprache-text | FALSE
Sprache -text | FALSE

**Comment by corylown** [comment] 2024-01-25 20:00
Based on the query debug output from Solr I am suspicious that this comment in the stopwords_punctuation.txt file is no longer true and hyphens are being treated as terms by Solr: https://github.com/sul-dlss/SearchWorks/blob/main/config/solr_configs/stopwords_punctuation.txt#L5

**Comment by corylown** [comment] 2024-01-25 21:47
@dnoneill  and I found some interesting things. It does look like Solr behavior changed at some point and hyphens are being treated as terms. This is causing problems in a couple of places. The proposed solution is to add `-` to the list of punctuation to treat as stopwords for fields we want indexed as a string. We also need to modify how we’re handling `text_anchored` type fields. I’ll write up more details with the findings, evidence, etc. and push up a proposed fix.

I will probably do this tomorrow morning because Solr has fried my brain

**Comment by corylown** [comment] 2024-01-30 20:56
Finally returning to this. Here is some debug info from Solr that helps explain why searches like `Sprache - text` don't return results:

There are two field types causing problems for us with this query (`text_anchored` and `string_punct_stop`).

These are simplified examples with only two fields being searched:

# string_punct_stop type fields

For a query searching for `Sprache - text` within a `text` field and a `string_punct_stop` field, here's how solr understands the query:

```
# solr_config
<str name="qf">
  title_245a_search # field type: text
  id_search # field type: string_punct_stop (stopword list does not include '-')
</str>
```

```
# debug output
+(
  DisjunctionMaxQuery(
    (
      id_search:Sprache | title_245a_search:sprach
    )~0.01
  )
  DisjunctionMaxQuery(
    (
      id_search:-
    )~0.01
  )
  DisjunctionMaxQuery(
    (
      id_search:text | title_245a_search:text
    )~0.01
  )
)~3
```

Solr is retaining `-` as a token and the min match settings are requiring matches for all three clauses for a document to match, note the `~3` after the closing parens. `id_search:-` would only match a document where the id_search field contains only `-`, so we get 0 matching documents.

To fix this we'd need to add `-` to the characters listed in the `stopwords_punctuation.txt` file to prevent Solr from treating these characters as standalone tokens. With this change the debug output becomes (and we return the correct document):

```
# debug output
+(
  DisjunctionMaxQuery(
    (
      id_search:Sprache | title_245a_search:sprach
    )~0.01
  )
  DisjunctionMaxQuery(
    (
      id_search:text | title_245a_search:text
    )~0.01
  )
)~2
```

We can apply this change without re-indexing because the stopword filter is only applied a query time. That's the good news.

# text_anchored type fields

For a query searching for `Sprache - text` within a `text` field and a `text_anchored` field, here's how solr understands the query:

```
# solr_config
<str name="qf">
  title_245a_exact_search # field type: text_anchored PatternReplaceCharFilterFactory not filtering out -
  title_245a_search       # field type: text
</str>

```

```
# debug output
+(
  DisjunctionMaxQuery(
    (
      title_245a_exact_search:aaaaaasprachezzzzzz | title_245a_search:sprach
    )~0.01
  )
  DisjunctionMaxQuery(
    (
      (
        (
          title_245a_exact_search:aaaaaazzzzzz title_245a_exact_search:"aaaaaa zzzzzz"~1
        )~2
      )
    )~0.01
  )
  DisjunctionMaxQuery(
    (
      title_245a_exact_search:aaaaaatextzzzzzz | title_245a_search:text
    )~0.01
  )
)~3
```

Solr is retaining a term where `-` had been in the query (the second/middle clause) and the min match settings are requiring matches for all three clauses for a document to match, note the `~3` after the closing parens. `title_245a_exact_search:aaaaaazzzzzz title_245a_exact_search:"aaaaaa zzzzzz"` is a query that I don't think would ever match a document so we get 0 matches.

To fix this problem we need to modify the `PatternReplaceCharFilterFactory` that's being applied at both index and query time. So:

```
<charFilter class="solr.PatternReplaceCharFilterFactory" pattern="^\s*(.*[\S&amp;&amp;[^\.\,:;/=&lt;&gt;\(\)\[\]\&amp;\|]])[\s\.\,:;/=&lt;&gt;\(\)\[\]\&amp;\|]*$" replacement="aaaaaa$1zzzzzz"/>
```
Would become with the addition of `\-` in the regex to filter out `-`:
```
<charFilter class="solr.PatternReplaceCharFilterFactory" pattern="^\s*(.*[\S&amp;&amp;[^\.\,\-:;/=&lt;&gt;\(\)\[\]\&amp;\|]])[\s\.\,\-:;/=&lt;&gt;\(\)\[\]\&amp;\|]*$" replacement="aaaaaa$1zzzzzz"/>
```

The challenge is that this filter is applied at both index and query time. I have a theory that the character filter portion of this is really only needed at query time, which would imply we could make this change without worrying about re-indexing everything, but I need to test this theory.

**Comment by corylown** [comment] 2024-02-01 20:12
Additionally looking into some regressions in hyphen handling in other queries (investigating why these test cases now fail: https://github.com/sul-dlss/sw_index_tests/blob/master/spec/punctuation/hyphen_spec.rb#L173-L204)

**Comment by corylown** [comment] 2024-02-01 22:25
`sow=true`  and `WordDelimiterGraphFilterFactory` are not so happy together:

query for `Deutsch-Sudwestafrikanische Zeitung` with `sow=true`
```
+(DisjunctionMaxQuery((((title_245a_search:deutschsudwestafrikanisch title_245a_search:"deutsch sudwestafrikanisch"~1)~2))~0.01) DisjunctionMaxQuery((title_245a_search:zeitung)~0.01))~2
```

query for` Deutsch-Sudwestafrikanische Zeitung` with `sow=false`
```
+(DisjunctionMaxQuery(((title_245a_search:deutschsudwestafrikanisch title_245a_search:"deutsch sudwestafrikanisch"))~0.01) DisjunctionMaxQuery((title_245a_search:zeitung)~0.01))~2
```

**Comment by corylown** [comment] 2024-02-02 19:32
If we stick with `sow=true` but want to improve results for queries like `Deutsch-Sudwestafrikanische Zeitung` we may need to add another field type for title fields that uses something like the `StandardTokenizerFactory` that tokenizes on most punctuation and whitespace, this is in addition to the existing `text` type field:

```
    <fieldType name="text_general" class="solr.TextField" positionIncrementGap="10000">
      <analyzer type="index">
        <tokenizer class="solr.StandardTokenizerFactory"/>
        <filter class="solr.ICUFoldingFilterFactory"/>  <!-- NFKC, case folding, diacritics removed -->
        <filter class="solr.SynonymGraphFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="false"/>
        <filter class="solr.FlattenGraphFilterFactory"/>
        <filter class="solr.SnowballPorterFilterFactory" language="English"/>
        <filter class="solr.RemoveDuplicatesTokenFilterFactory" />
      </analyzer>
      <analyzer type="query">
        <tokenizer class="solr.StandardTokenizerFactory"/>
        <filter class="solr.ICUFoldingFilterFactory"/>  <!-- NFKC, case folding, diacritics removed -->
        <filter class="solr.SynonymGraphFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="false"/>
        <filter class="solr.SnowballPorterFilterFactory" language="English"/>
        <filter class="solr.RemoveDuplicatesTokenFilterFactory" />
      </analyzer>
    </fieldType>

```

**Comment by corylown** [comment] 2024-02-06 13:27
Searches  with space hyphen space are now fixed in prod: https://searchworks.stanford.edu/?search_field=search&q=Sprache+-+text+-+system

**Comment by jcoyne** [comment] 2024-02-06 14:05
To be perfectly clear, this only works if you surround the hyphens with spaces.  The result set is different if you omit the spaces, e.g. https://searchworks.stanford.edu/?search_field=search&q=Sprache-text-system, but I think that was what was asked for.

**Comment by corylown** [comment] 2024-02-06 18:43
Queries with no space surrounding the hyphen, such as in `sprache-text-system` may be fixed by setting `sow=false` (to be tested in this change: https://github.com/sul-dlss/sul-solr-configs/pull/304) or by adding a new field type that splits on whitespace and punctuation, something like the `text_general` field in my comment above.

**Closed** 2024-02-08 17:24 UTC
