### ISSUE TITLE
Refactor item_display field value format

### ISSUE THREAD

**Issue by corylown** [sul-dlss/searchworks_traject_indexer#859] opened 2023-05-09 14:39 UTC
The `item_display` field currently stores item information in a ` -|- ` delimited string format. It would be easier to read and understand the values in this field if we stored a JSON blob with meaningful key/value pairs instead. SearchWorks would also need to be updated to use this different format.

**Comment by thatbudakguy** [comment] 2023-05-09 17:36
duplicate of #714?

**Comment by corylown** [comment] 2023-05-09 18:01
@thatbudakguy I don't think these are duplicates. #714 is specifically about how the code is structured and eliminating duplication of logic. Completing #714 would not result in any change in the data produced. #859 is about changing the output format of the data to be a JSON string.

**Comment by thatbudakguy** [comment] 2023-05-09 19:52
gotcha, thanks for explaining

**Closed** 2023-07-27 12:46 UTC
Labels: after-folio
